taskKey="com.javarush.task.jdk13.task09.task0913"\n\nИсключения

Есть метод, который выбрасывает два исключения, унаследованные от Exception, и два унаследованных от RuntimeException:
NullPointerException, ArithmeticException, FileNotFoundException, URISyntaxException.

Нужно перехватить NullPointerException и FileNotFoundException, но не перехватывать
ArithmeticException и URISyntaxException. Как это сделать?


Требования:
1.	В методе main необходимо вызывать метод method1.
2.	В методе main необходимо перехватывать исключение NullPointerException.
3.	В методе main необходимо перехватывать исключение FileNotFoundException.
4.	В методе main исключение ArithmeticException не перехватывать.
5.	В методе main исключение URISyntaxException не перехватывать.
6.	Метод method1 не изменять.


